apiVersion: apps/v1
kind: Deployment
metadata:
  name: backdeploy
spec:
  selector:
    matchLabels:
      app: backendapp
  template:
    metadata:
      labels:
        app: backendapp
    spec:
      containers:
      - name: easybackend
        image: omkarsahastrabudhe/backend:v2
        env:
          - name: HOST_NAME
            value: dbservice
          - name:  DB_NAME
            value: student_db
          - name:  DB_USERNAME
            value: root
          - name: DB_PASSWD
            value: 'omkar@123'  
        ports:
          - containerPort:  8080

---
apiVersion: v1
kind: Service
metadata: 
    name: backendservice
spec: 
   type: ClusterIP
   selector: 
      app: backendapp
   ports:
     - port: 8080
       containerPort: 8080         
