apiVersion: apps/v1
kind: Deployment
metadata:
  name: backdeploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backendapp
  template:
    metadata:
      labels:
        app: backendapp
    spec:
      containers:
      - name: easybackend
        image: omkarsahastrabudhe/backend:v2
        env:
          - name: HOST_NAME
            value: dbservice
          - name:  DB_NAME
            value: student_db
          - name:  DB_USERNAME
            value: root
          - name: DB_PASSWD
            value: 'omkar@123'  
        ports:
          - containerPort:  8080
        resources:
           requests:
              cpu: "100m"
              memory: "128Mi"
           limits:
               cpu: "200m"
               memory: "200Mi"                  

---
apiVersion: v1
kind: Service
metadata: 
    name: backendservice
spec: 
   type: ClusterIP
   selector: 
      app: backendapp
   ports:
     - port: 8080
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata: 
    name: hpabackend
spec:
   scaleTargetRef:
     apiVersion: apps/v1
     kind: Deployment
     name: backdeploy 
   minReplicas: 1
   maxReplicas: 5
   metrics:
    - type: Resource
      resource:
       name: cpu
       target: 
         type: Utilization
         averageUtilization: 80    

